language: cpp

compiler:
  - gcc

before_install:
  - git submodule update --init --recursive

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y g++-4.7 g++-4.7-multilib lib32z1 lib32z1-dev libc6-i386 libc6-dev-i386; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

script: mkdir build && cd build && cmake .. && make
os:
  - linux